### ISSUE TITLE
Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by MartinMuzatko** [andru255/gulp-recursive-folder#2]
Whenever I run recursiveFolder, I get this error. No matter what code is in the gulp task - even if it is empty!

```
[15:24:50] TypeError: Cannot read property 'pipe' of undefined
    at node_modules/event-stream/index.js:43:6
    at Array.forEach (native)
    at es.concat.es.merge (node_modules/event-stream/index.js:42:11)
    at Gulp.<anonymous> (node_modules/gulp-recursive-folder/index.js:58:25)
    at module.exports (node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)


```

**Comment by cillosis** [comment]
I just ran into the same issue in one of my projects...still looking into why it isn't working. I suspect it is an issue in the `event-stream` package though as I am not using `gulp-recursive-folder`.

**Comment by andru255** [comment]
It's very strange, thanks @MartinMuzatko and @cillosis, I create a folder called "test" for validate the entire funcionality, but I try to repeat that bug

**Comment by andru255** [comment]
thanks to @HitkoDev, It runs good in the new release, please try to test again @MartinMuzatko, If still have errors please print the error again.
